# Generated by Django 4.2.23 on 2025-08-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=10, verbose_name="Цена"
            ),
            preserve_default=False,
        ),
    ]
